server:
  port: 8008

spring:
  application:
    name: pcs-evaluation
  #  autoconfigure:
  #    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
  activiti:
    check-process-definitions: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yang1290
    url: jdbc:mysql://10.103.241.66:3306/pcs?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
  redis:
    host: 127.0.0.1
    port: 6379
    password: lizhijie
    timeout: 0